language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: jE9boMFli3T1QIm6dUXd9Zfov3BygWt+csucqkpGLw0hn4CP9VDWBTiFk0jCH4RSeeOUVxUZGjr0AsP6WLkzW3+ZIZWGCQJPkl4z2QVuiXnzzY5FmLpQyfLNJznF4ZI1O8E75K9eI6Gn29vwMcqzzmZnSgXrHm56naPVFmGl54CVFbazt/GYCkHD5vCQuaa6VT3qBAsE5CPGtpEnOfAZKbkZExVztwgwRq3Q7srfXKPucmqACcPcpIVK16z8MNAshXpqbZs3DAw2lqNfyt5PsrZuGYdzvG3Sbc6od1fptlFM2pNWKkc3PLyLL/7eYeuUgFFGmee7d8JMo2LyLpgLcbwLq4D3g+17sSfps9K4ca/etJvvu1JRhxwioXd63yi9b0JYLWzlNgtgkin09uXbQTScknI0JyfxSdKQgWMIHMob7LC81LUbu/fkMCK/rm8HD1UCvXIvXULBB+Jzmagrf67gtGwtaYKJnW/Qnd6PM3IuCioOhZKjc0oI0VAAVJjZPmfyS09Fpp5XMKetiebC3C7pFdOQbs2EfDczoZ4WTQbD7O7NY+rl7pLLxKq+YA2qsEUBCpnXSjJuxdxcYpuCnUsnmd8Z2Xbl3Nwvm71h34QFG0WpR8HhBW8MLXOY8llfP0vqbcd1B1bf5oA9oW+2bc8xWJEvAMeBBWlziz9nyQM=
  app: node-shopping-list-integration-tests
  on:
    repo: Daniel-Slabaugh/node-shopping-list-integration-tests
